server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true  #当遇到同样名字的时候，是否允许覆盖注册
    devtools:
      restart:
        enabled: true  #设置开启热部署
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效
    thymeleaf:
      prefix: classpath:/templates/  #页面所在路径
      suffix: .html
      mode: HTML
      encoding: utf-8
      cache: false
      servlet:
        content-type: text/html
      resources:
        chain:
          strategy:
            content:
              enabled: true
              paths: /**
  datasource:
    test:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&&serverTimezone=UTC
      username: root
      password: jiazhangjia217
    test2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&&serverTimezone=UTC
      username: root
      password: jiazhangjia217
    mytest:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8&&serverTimezone=UTC
      username: root
      password: jiazhangjia217


mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.sayimfun.moredatasource.entity
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名

# 打印sql
logging:
  level:
    com.sayimfun.moredatasource.mapper: debug