spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    test:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&&serverTimezone=UTC
      username: root
      password: jiazhangjia217
    test2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&&serverTimezone=UTC
      username: root
      password: jiazhangjia217
    mytest:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8&&serverTimezone=UTC
      username: root
      password: jiazhangjia217

server:
  port: 8081